// Code generated by sqlc-gen-sqlx v0.2.6. DO NOT EDIT.
// sqlc version: v1.31.1

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

pub trait AsExecutor {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite>;
}
impl AsExecutor for sqlx::SqlitePool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite> {
        &*self
    }
}
impl AsExecutor for &sqlx::SqlitePool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite> {
        *self
    }
}
impl AsExecutor for sqlx::SqliteConnection {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite> {
        &mut *self
    }
}
impl AsExecutor for sqlx::Transaction<'_, sqlx::Sqlite> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite> {
        &mut **self
    }
}
impl AsExecutor for sqlx::pool::PoolConnection<sqlx::Sqlite> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite> {
        &mut **self
    }
}
impl<T: AsExecutor + ?Sized> AsExecutor for &mut T {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Sqlite> {
        (**self).as_executor()
    }
}
#[derive(Debug, Clone)]
pub struct CreateAuthorParams {
    pub name: String,
    pub bio: Option<String>,
    pub rating: f64,
}
pub const CREATE_AUTHOR: &str = "INSERT INTO authors (name, bio, rating)\nVALUES (?, ?, ?)";
pub async fn create_author<E: AsExecutor>(
    mut db: E,
    arg: CreateAuthorParams,
) -> Result<i64, sqlx::Error> {
    let result = sqlx::query(CREATE_AUTHOR)
        .bind(arg.name)
        .bind(arg.bio)
        .bind(arg.rating)
        .execute(db.as_executor())
        .await?;
    Ok(result.last_insert_rowid())
}
pub const GET_AUTHOR: &str = "SELECT id, name, bio, rating\nFROM authors\nWHERE id = ?";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
    pub rating: f64,
}
pub async fn get_author<E: AsExecutor>(mut db: E, id: i64) -> Result<GetAuthorRow, sqlx::Error> {
    sqlx::query_as::<_, GetAuthorRow>(GET_AUTHOR)
        .bind(id)
        .fetch_one(db.as_executor())
        .await
}
pub const LIST_AUTHORS_BY_IDS: &str =
    "SELECT id, name, bio, rating\nFROM authors\nWHERE id IN (/*SLICE:ids*/?)\nORDER BY id";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListAuthorsByIdsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
    pub rating: f64,
}
pub async fn list_authors_by_ids<E: AsExecutor>(
    mut db: E,
    id: Vec<i64>,
) -> Result<Vec<ListAuthorsByIdsRow>, sqlx::Error> {
    let mut sql = LIST_AUTHORS_BY_IDS.to_string();
    {
        let slice_len = (id).len();
        let replacement = if slice_len == 0 {
            "NULL".to_string()
        } else {
            std::iter::repeat_n("?", slice_len)
                .collect::<Vec<_>>()
                .join(", ")
        };
        sql = sql.replace("/*SLICE:ids*/?", &replacement);
    }
    let mut query = sqlx::query_as::<_, ListAuthorsByIdsRow>(sqlx::AssertSqlSafe(sql));
    for value in id {
        query = query.bind(value);
    }
    query.fetch_all(db.as_executor()).await
}
pub const DELETE_AUTHOR_ROWS: &str = "DELETE FROM authors\nWHERE id = ?";
pub async fn delete_author_rows<E: AsExecutor>(mut db: E, id: i64) -> Result<u64, sqlx::Error> {
    let result = sqlx::query(DELETE_AUTHOR_ROWS)
        .bind(id)
        .execute(db.as_executor())
        .await?;
    Ok(result.rows_affected())
}
