//! Snapshot and behaviour tests for `engine: mysql`.
//!
//! The PostgreSQL equivalents live in `tests/codegen.rs`; this file covers the
//! places where the two backends genuinely diverge — driver types, `?`
//! placeholders, `:execlastid`, and the MySQL type table.

use buffa::Message as _;
use sqlc_gen_sqlx::plugin::{
    Catalog, Column, Enum, GenerateRequest, GenerateResponse, Identifier, Parameter, Query, Schema,
    Settings, Table,
};
use sqlc_gen_sqlx::run_with_bytes;

fn column(name: &str, db_type: &str, not_null: bool) -> Column {
    Column {
        name: name.to_string(),
        r#type: Some(Identifier {
            name: db_type.to_string(),
            ..Default::default()
        })
        .into(),
        not_null,
        ..Default::default()
    }
}

/// A `sqlc.slice()` parameter. `name` is the slice's own name (and the one in
/// the `/*SLICE:name*/` marker); `original_name` is the column it is compared
/// against.
fn slice_column(name: &str, original_name: &str, db_type: &str) -> Column {
    Column {
        is_sqlc_slice: true,
        is_named_param: true,
        original_name: original_name.to_string(),
        ..column(name, db_type, true)
    }
}

fn param(number: i32, col: Column) -> Parameter {
    Parameter {
        number,
        column: Some(col).into(),
        ..Default::default()
    }
}

fn authors_table() -> Table {
    Table {
        rel: Some(Identifier {
            name: "authors".to_string(),
            ..Default::default()
        })
        .into(),
        columns: vec![
            column("id", "bigint", true),
            column("name", "varchar(255)", true),
            column("bio", "text", false),
        ],
        ..Default::default()
    }
}

fn generate(engine: &str, queries: Vec<Query>) -> Result<String, String> {
    generate_with(engine, queries, vec![])
}

fn generate_with(engine: &str, queries: Vec<Query>, enums: Vec<Enum>) -> Result<String, String> {
    let request = GenerateRequest {
        settings: Some(Settings {
            engine: engine.to_string(),
            ..Default::default()
        })
        .into(),
        catalog: Some(Catalog {
            default_schema: "sqlc_test".to_string(),
            schemas: vec![Schema {
                name: "sqlc_test".to_string(),
                tables: vec![authors_table()],
                enums,
                ..Default::default()
            }],
            ..Default::default()
        })
        .into(),
        queries,
        plugin_options: b"{}".to_vec(),
        sqlc_version: "1.0.0-test".to_string(),
        ..Default::default()
    };

    let out = run_with_bytes(&request.encode_to_vec()).map_err(|e| e.to_string())?;
    let resp = GenerateResponse::decode_from_slice(&out).expect("decode response");
    Ok(String::from_utf8(resp.files[0].contents.clone()).expect("utf-8 output"))
}

fn assert_snapshot(name: &str, code: &str) {
    let mut settings = insta::Settings::clone_current();
    settings.add_filter(
        r"// Code generated by sqlc-gen-sqlx v[0-9A-Za-z][0-9A-Za-z.+-]*\. DO NOT EDIT\.",
        "// Code generated by sqlc-gen-sqlx v[VERSION]. DO NOT EDIT.",
    );
    settings.add_filter(
        r"// sqlc version: [0-9A-Za-z][0-9A-Za-z.+-]*",
        "// sqlc version: [VERSION]",
    );
    settings.bind(|| insta::assert_snapshot!(name, code));
}

#[test]
fn as_executor_targets_the_mysql_driver() {
    let code = generate("mysql", vec![]).expect("generate");
    assert_snapshot("mysql_as_executor", &code);
    for expected in [
        "Database = sqlx::MySql",
        "impl AsExecutor for sqlx::MySqlPool",
        "impl AsExecutor for sqlx::MySqlConnection",
        "sqlx::Transaction<'_, sqlx::MySql>",
        "sqlx::pool::PoolConnection<sqlx::MySql>",
    ] {
        assert!(code.contains(expected), "missing {expected} in:\n{code}");
    }
    assert!(!code.contains("Pg"), "leaked a PostgreSQL type in:\n{code}");
}

#[test]
fn one_maps_mysql_column_types() {
    let query = Query {
        name: "GetAuthor".to_string(),
        cmd: ":one".to_string(),
        text: "SELECT id, name, bio FROM authors WHERE id = ?".to_string(),
        columns: vec![
            column("id", "bigint", true),
            column("name", "varchar(255)", true),
            column("bio", "text", false),
        ],
        params: vec![param(1, column("id", "bigint", true))],
        ..Default::default()
    };
    let code = generate("mysql", vec![query]).expect("generate");
    assert_snapshot("mysql_one", &code);
    assert!(
        code.contains("pub id: i64"),
        "expected i64 id field in:\n{code}"
    );
    assert!(
        code.contains("pub name: String"),
        "expected varchar(255) to map to String in:\n{code}"
    );
    assert!(
        code.contains("pub bio: Option<String>"),
        "expected nullable text to map to Option<String> in:\n{code}"
    );
}

#[test]
fn execresult_returns_the_mysql_query_result() {
    let query = Query {
        name: "DeleteAuthor".to_string(),
        cmd: ":execresult".to_string(),
        text: "DELETE FROM authors WHERE id = ?".to_string(),
        params: vec![param(1, column("id", "bigint", true))],
        ..Default::default()
    };
    let code = generate("mysql", vec![query]).expect("generate");
    assert_snapshot("mysql_execresult", &code);
    assert!(
        code.contains("sqlx::mysql::MySqlQueryResult"),
        "expected MySqlQueryResult in:\n{code}"
    );
}

#[test]
fn execlastid_returns_the_generated_key() {
    let query = Query {
        name: "CreateAuthor".to_string(),
        cmd: ":execlastid".to_string(),
        text: "INSERT INTO authors (name, bio) VALUES (?, ?)".to_string(),
        params: vec![
            param(1, column("name", "varchar(255)", true)),
            param(2, column("bio", "text", false)),
        ],
        ..Default::default()
    };
    let code = generate("mysql", vec![query]).expect("generate");
    assert_snapshot("mysql_execlastid", &code);
    assert!(
        code.contains("-> Result<u64, sqlx::Error>"),
        "expected u64 return in:\n{code}"
    );
    assert!(
        code.contains("result.last_insert_id()"),
        "expected last_insert_id() in:\n{code}"
    );
}

#[test]
fn execlastid_needs_no_returning_columns() {
    // The PostgreSQL generator requires a RETURNING column here; MySQL reads
    // the key off the query result, so a column-less query must still work.
    let query = Query {
        name: "CreateAuthor".to_string(),
        cmd: ":execlastid".to_string(),
        text: "INSERT INTO authors (name) VALUES (?)".to_string(),
        params: vec![param(1, column("name", "text", true))],
        columns: vec![],
        ..Default::default()
    };
    generate("mysql", vec![query.clone()]).expect("mysql :execlastid without columns");

    let err = generate("postgresql", vec![query]).expect_err("postgres needs RETURNING");
    assert!(
        err.contains("RETURNING"),
        "expected a RETURNING hint in: {err}"
    );
}

#[test]
fn slice_param_expands_into_ordinal_placeholders() {
    // Mirrors what sqlc reports: it lifts `sqlc.slice()` out of the ordinal
    // numbering, so the slice carries the *higher* number despite coming first
    // in the text, and its column name is the slice's own (`ids`) while
    // `original_name` is the compared column (`id`).
    let query = Query {
        name: "ListAuthorsByIds".to_string(),
        cmd: ":many".to_string(),
        text: "SELECT id, name FROM authors WHERE id IN (/*SLICE:ids*/?) AND name = ?".to_string(),
        columns: vec![
            column("id", "bigint", true),
            column("name", "varchar", true),
        ],
        params: vec![
            param(2, slice_column("ids", "id", "bigint")),
            param(1, column("name", "varchar", true)),
        ],
        ..Default::default()
    };
    let code = generate("mysql", vec![query]).expect("generate");
    assert_snapshot("mysql_slice_param", &code);
    assert!(
        code.contains(r#"sql.replace("/*SLICE:ids*/?", &replacement)"#),
        "expected the slice marker to be rewritten in:\n{code}"
    );
    assert!(
        code.contains(r#"repeat_n("?", slice_len)"#),
        "expected ordinal placeholder expansion in:\n{code}"
    );
    // Ordinal placeholders are bound in text order, so the slice binds before
    // the scalar even though sqlc numbered it second.
    let slice_bind = code.find("for value in arg.id").expect("slice bind");
    let scalar_bind = code.find("query.bind(arg.name)").expect("scalar bind");
    assert!(
        slice_bind < scalar_bind,
        "slice must bind before the trailing scalar in:\n{code}"
    );
    // Ordinal placeholders keep their positions, so nothing gets renumbered.
    assert!(
        !code.contains("__SQLC_PARAM_"),
        "MySQL must not renumber placeholders in:\n{code}"
    );
}

#[test]
fn enums_omit_the_postgres_type_name_attribute() {
    let status = Enum {
        name: "authors_status".to_string(),
        vals: vec!["active".to_string(), "banned".to_string()],
        ..Default::default()
    };
    let query = Query {
        name: "GetStatus".to_string(),
        cmd: ":one".to_string(),
        text: "SELECT status FROM authors WHERE id = ?".to_string(),
        columns: vec![column("status", "authors_status", true)],
        params: vec![param(1, column("id", "bigint", true))],
        ..Default::default()
    };
    let code = generate_with("mysql", vec![query], vec![status]).expect("generate");
    assert_snapshot("mysql_enum", &code);
    assert!(
        code.contains("pub enum AuthorsStatus"),
        "expected the enum type in:\n{code}"
    );
    assert!(
        code.contains(r#"#[sqlx(rename = "active")]"#),
        "expected variant renames in:\n{code}"
    );
    assert!(
        !code.contains("type_name"),
        "MySQL enums must not carry #[sqlx(type_name)] in:\n{code}"
    );
}

#[test]
fn copyfrom_builds_a_mysql_query_builder() {
    let query = Query {
        name: "BulkCreateAuthors".to_string(),
        cmd: ":copyfrom".to_string(),
        text: "INSERT INTO authors (name, bio) VALUES (?, ?)".to_string(),
        params: vec![
            param(1, column("name", "varchar(255)", true)),
            param(2, column("bio", "text", false)),
        ],
        ..Default::default()
    };
    let code = generate("mysql", vec![query]).expect("generate");
    assert_snapshot("mysql_copyfrom", &code);
    let builder = code.split_whitespace().collect::<Vec<_>>().join(" ");
    assert!(
        builder.contains("sqlx::QueryBuilder::< sqlx::MySql, >::new"),
        "expected a MySQL query builder in:\n{code}"
    );
}

#[test]
fn covers_the_mysql_scalar_type_table() {
    let cases: &[(&str, &str)] = &[
        ("tinyint", "i8"),
        ("tinyint unsigned", "u8"),
        ("smallint", "i16"),
        ("mediumint", "i32"),
        ("int(11)", "i32"),
        ("int unsigned", "u32"),
        ("bigint", "i64"),
        ("bigint unsigned", "u64"),
        ("boolean", "bool"),
        ("float", "f32"),
        ("double", "f64"),
        ("decimal(10,2)", "bigdecimal::BigDecimal"),
        ("char(3)", "String"),
        ("varchar(255)", "String"),
        ("longtext", "String"),
        ("varbinary(16)", "Vec<u8>"),
        ("longblob", "Vec<u8>"),
        ("json", "serde_json::Value"),
        ("timestamp", "chrono::DateTime<chrono::Utc>"),
        ("datetime", "chrono::NaiveDateTime"),
        ("date", "chrono::NaiveDate"),
        ("time", "chrono::NaiveTime"),
    ];

    let columns = cases
        .iter()
        .enumerate()
        .map(|(i, (db_type, _))| column(&format!("c{i}"), db_type, true))
        .collect::<Vec<_>>();
    let query = Query {
        name: "AllTypes".to_string(),
        cmd: ":one".to_string(),
        text: "SELECT * FROM all_types".to_string(),
        columns,
        ..Default::default()
    };
    let code = generate("mysql", vec![query]).expect("generate");

    for (i, (db_type, rust_type)) in cases.iter().enumerate() {
        let expected = format!("pub c_{i}: {rust_type},");
        assert!(
            code.contains(&expected),
            "{db_type} should map to {rust_type}; missing `{expected}` in:\n{code}"
        );
    }
}

#[test]
fn unknown_engine_is_rejected() {
    let err = generate("oracle", vec![]).expect_err("oracle is not supported");
    assert!(err.contains("oracle"), "expected the engine name in: {err}");
    assert!(
        err.contains("postgresql") && err.contains("mysql"),
        "expected the supported engines to be listed in: {err}"
    );
}

#[test]
fn missing_engine_still_generates_postgres() {
    // sqlc always sends settings, but requests built by hand (and older
    // releases) may not. Keep the historical default rather than failing.
    let request = GenerateRequest {
        plugin_options: b"{}".to_vec(),
        sqlc_version: "1.0.0-test".to_string(),
        ..Default::default()
    };
    let out = run_with_bytes(&request.encode_to_vec()).expect("generate");
    let resp = GenerateResponse::decode_from_slice(&out).unwrap();
    let code = String::from_utf8(resp.files[0].contents.clone()).unwrap();
    assert!(
        code.contains("sqlx::PgPool"),
        "expected the PostgreSQL default in:\n{code}"
    );
}
