//! Snapshot and behaviour tests for `engine: sqlite`.
//!
//! The PostgreSQL equivalents live in `tests/codegen.rs` and the MySQL ones in
//! `tests/codegen_mysql.rs`; this file covers what is specific to SQLite —
//! driver types, `:execlastid` via `last_insert_rowid()`, and the SQLite type
//! table, whose declared-type names are unlike either other engine's.

use buffa::Message as _;
use sqlc_gen_sqlx::plugin::{
    Catalog, Column, GenerateRequest, GenerateResponse, Identifier, Parameter, Query, Schema,
    Settings, Table,
};
use sqlc_gen_sqlx::run_with_bytes;

fn column(name: &str, db_type: &str, not_null: bool) -> Column {
    Column {
        name: name.to_string(),
        r#type: Some(Identifier {
            name: db_type.to_string(),
            ..Default::default()
        })
        .into(),
        not_null,
        ..Default::default()
    }
}

/// A `sqlc.slice()` parameter. `name` is the slice's own name (and the one in
/// the `/*SLICE:name*/` marker); `original_name` is the column it is compared
/// against.
fn slice_column(name: &str, original_name: &str, db_type: &str) -> Column {
    Column {
        is_sqlc_slice: true,
        is_named_param: true,
        original_name: original_name.to_string(),
        ..column(name, db_type, true)
    }
}

fn param(number: i32, col: Column) -> Parameter {
    Parameter {
        number,
        column: Some(col).into(),
        ..Default::default()
    }
}

fn authors_table() -> Table {
    Table {
        rel: Some(Identifier {
            name: "authors".to_string(),
            ..Default::default()
        })
        .into(),
        columns: vec![
            column("id", "INTEGER", true),
            column("name", "TEXT", true),
            column("bio", "TEXT", false),
        ],
        ..Default::default()
    }
}

fn generate(queries: Vec<Query>) -> Result<String, String> {
    let request = GenerateRequest {
        settings: Some(Settings {
            engine: "sqlite".to_string(),
            ..Default::default()
        })
        .into(),
        catalog: Some(Catalog {
            default_schema: "main".to_string(),
            schemas: vec![Schema {
                name: "main".to_string(),
                tables: vec![authors_table()],
                ..Default::default()
            }],
            ..Default::default()
        })
        .into(),
        queries,
        plugin_options: b"{}".to_vec(),
        sqlc_version: "1.0.0-test".to_string(),
        ..Default::default()
    };

    let out = run_with_bytes(&request.encode_to_vec()).map_err(|e| e.to_string())?;
    let resp = GenerateResponse::decode_from_slice(&out).expect("decode response");
    Ok(String::from_utf8(resp.files[0].contents.clone()).expect("utf-8 output"))
}

fn assert_snapshot(name: &str, code: &str) {
    let mut settings = insta::Settings::clone_current();
    settings.add_filter(
        r"// Code generated by sqlc-gen-sqlx v[0-9A-Za-z][0-9A-Za-z.+-]*\. DO NOT EDIT\.",
        "// Code generated by sqlc-gen-sqlx v[VERSION]. DO NOT EDIT.",
    );
    settings.add_filter(
        r"// sqlc version: [0-9A-Za-z][0-9A-Za-z.+-]*",
        "// sqlc version: [VERSION]",
    );
    settings.bind(|| insta::assert_snapshot!(name, code));
}

#[test]
fn as_executor_targets_the_sqlite_driver() {
    let code = generate(vec![]).expect("generate");
    assert_snapshot("sqlite_as_executor", &code);
    for expected in [
        "Database = sqlx::Sqlite",
        "impl AsExecutor for sqlx::SqlitePool",
        "impl AsExecutor for sqlx::SqliteConnection",
        "sqlx::Transaction<'_, sqlx::Sqlite>",
        "sqlx::pool::PoolConnection<sqlx::Sqlite>",
    ] {
        assert!(code.contains(expected), "missing {expected} in:\n{code}");
    }
    assert!(!code.contains("Pg"), "leaked a PostgreSQL type in:\n{code}");
    assert!(!code.contains("MySql"), "leaked a MySQL type in:\n{code}");
}

#[test]
fn one_maps_sqlite_column_types() {
    let query = Query {
        name: "GetAuthor".to_string(),
        cmd: ":one".to_string(),
        text: "SELECT id, name, bio FROM authors WHERE id = ?".to_string(),
        columns: vec![
            column("id", "INTEGER", true),
            column("name", "TEXT", true),
            column("bio", "TEXT", false),
        ],
        params: vec![param(1, column("id", "INTEGER", true))],
        ..Default::default()
    };
    let code = generate(vec![query]).expect("generate");
    assert_snapshot("sqlite_one", &code);
    assert!(
        code.contains("pub id: i64"),
        "SQLite stores every integer as 64-bit; expected i64 in:\n{code}"
    );
    assert!(
        code.contains("pub bio: Option<String>"),
        "expected nullable TEXT to map to Option<String> in:\n{code}"
    );
}

#[test]
fn execresult_returns_the_sqlite_query_result() {
    let query = Query {
        name: "DeleteAuthor".to_string(),
        cmd: ":execresult".to_string(),
        text: "DELETE FROM authors WHERE id = ?".to_string(),
        params: vec![param(1, column("id", "INTEGER", true))],
        ..Default::default()
    };
    let code = generate(vec![query]).expect("generate");
    assert_snapshot("sqlite_execresult", &code);
    assert!(
        code.contains("sqlx::sqlite::SqliteQueryResult"),
        "expected SqliteQueryResult in:\n{code}"
    );
}

#[test]
fn execlastid_returns_the_inserted_rowid() {
    let query = Query {
        name: "CreateAuthor".to_string(),
        cmd: ":execlastid".to_string(),
        text: "INSERT INTO authors (name, bio) VALUES (?, ?)".to_string(),
        params: vec![
            param(1, column("name", "TEXT", true)),
            param(2, column("bio", "TEXT", false)),
        ],
        ..Default::default()
    };
    let code = generate(vec![query]).expect("generate");
    assert_snapshot("sqlite_execlastid", &code);
    // SQLite's rowid is signed, unlike MySQL's unsigned last-insert-id.
    assert!(
        code.contains("-> Result<i64, sqlx::Error>"),
        "expected i64 return in:\n{code}"
    );
    assert!(
        code.contains("result.last_insert_rowid()"),
        "expected last_insert_rowid() in:\n{code}"
    );
}

#[test]
fn slice_param_expands_into_ordinal_placeholders() {
    let query = Query {
        name: "ListAuthorsByIds".to_string(),
        cmd: ":many".to_string(),
        text: "SELECT id, name FROM authors WHERE id IN (/*SLICE:ids*/?) AND name = ?".to_string(),
        columns: vec![column("id", "INTEGER", true), column("name", "TEXT", true)],
        params: vec![
            param(2, slice_column("ids", "id", "INTEGER")),
            param(1, column("name", "TEXT", true)),
        ],
        ..Default::default()
    };
    let code = generate(vec![query]).expect("generate");
    assert_snapshot("sqlite_slice_param", &code);
    assert!(
        code.contains(r#"sql.replace("/*SLICE:ids*/?", &replacement)"#),
        "expected the slice marker to be rewritten in:\n{code}"
    );
    // SQLite shares MySQL's ordinal placeholders: binds follow the query text.
    let slice_bind = code.find("for value in arg.id").expect("slice bind");
    let scalar_bind = code.find("query.bind(arg.name)").expect("scalar bind");
    assert!(
        slice_bind < scalar_bind,
        "slice must bind before the trailing scalar in:\n{code}"
    );
    assert!(
        !code.contains("__SQLC_PARAM_"),
        "SQLite must not renumber placeholders in:\n{code}"
    );
}

#[test]
fn covers_the_sqlite_declared_type_table() {
    // SQLite declares types in whatever spelling the schema author used; sqlc
    // passes them through verbatim, so the resolver has to handle widths and
    // multi-word names.
    let cases: &[(&str, &str)] = &[
        ("INTEGER", "i64"),
        ("INT", "i64"),
        ("TINYINT", "i64"),
        ("BIGINT", "i64"),
        ("UNSIGNED BIG INT", "i64"),
        ("INT2", "i64"),
        ("TEXT", "String"),
        ("CLOB", "String"),
        ("VARCHAR(255)", "String"),
        ("VARYING CHARACTER(255)", "String"),
        ("NATIVE CHARACTER(70)", "String"),
        ("BLOB", "Vec<u8>"),
        ("REAL", "f64"),
        ("DOUBLE PRECISION", "f64"),
        ("FLOAT", "f64"),
        ("NUMERIC", "f64"),
        ("DECIMAL(10,5)", "f64"),
        ("BOOLEAN", "bool"),
        ("DATE", "chrono::NaiveDate"),
        ("DATETIME", "chrono::NaiveDateTime"),
        ("TIMESTAMP", "chrono::NaiveDateTime"),
    ];

    let columns = cases
        .iter()
        .enumerate()
        .map(|(i, (db_type, _))| column(&format!("c{i}"), db_type, true))
        .collect::<Vec<_>>();
    let query = Query {
        name: "AllTypes".to_string(),
        cmd: ":one".to_string(),
        text: "SELECT * FROM all_types".to_string(),
        columns,
        ..Default::default()
    };
    let code = generate(vec![query]).expect("generate");

    for (i, (db_type, rust_type)) in cases.iter().enumerate() {
        let expected = format!("pub c_{i}: {rust_type},");
        assert!(
            code.contains(&expected),
            "{db_type} should map to {rust_type}; missing `{expected}` in:\n{code}"
        );
    }
}

#[test]
fn unknown_engine_error_lists_sqlite() {
    let request = GenerateRequest {
        settings: Some(Settings {
            engine: "oracle".to_string(),
            ..Default::default()
        })
        .into(),
        plugin_options: b"{}".to_vec(),
        ..Default::default()
    };
    let err = run_with_bytes(&request.encode_to_vec())
        .expect_err("oracle is not supported")
        .to_string();
    assert!(
        err.contains("sqlite"),
        "expected sqlite among the supported engines in: {err}"
    );
}
